-- =========================================================================
-- Shivam Grover 3D Portfolio — Supabase PostgreSQL Database Schema
-- Production-Ready, Relational User Profiles & Contact Inquiries with RLS
-- =========================================================================

-- 1. Enable UUID Extension (pgcrypto is built into Supabase / PostgreSQL)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =========================================================================
-- Table: public.profiles
-- Linked to Supabase Auth (auth.users)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL UNIQUE,
    avatar_url TEXT,
    provider TEXT NOT NULL DEFAULT 'google',
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    last_login_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Indices for rapid lookup & auth matching
CREATE INDEX IF NOT EXISTS idx_profiles_auth_user_id ON public.profiles(auth_user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);

-- Comments for database documentation
COMMENT ON TABLE public.profiles IS 'Authenticated user profiles linked to Google / Supabase Auth accounts.';
COMMENT ON COLUMN public.profiles.auth_user_id IS 'Foreign key reference to auth.users.id generated by Supabase Auth.';

-- =========================================================================
-- Table: public.contact_submissions
-- Stores inbound portfolio contact form messages securely
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL CHECK (char_length(name) >= 2 AND char_length(name) <= 100),
    email TEXT NOT NULL CHECK (char_length(email) >= 5 AND char_length(email) <= 120),
    subject TEXT NOT NULL DEFAULT 'New Portfolio Inquiry' CHECK (char_length(subject) <= 150),
    message TEXT NOT NULL CHECK (char_length(message) >= 5 AND char_length(message) <= 5000),
    phone TEXT CHECK (phone IS NULL OR char_length(phone) <= 30),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'replied', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Indices for submissions management
CREATE INDEX IF NOT EXISTS idx_contact_submissions_user_id ON public.contact_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_contact_submissions_created_at ON public.contact_submissions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contact_submissions_status ON public.contact_submissions(status);

COMMENT ON TABLE public.contact_submissions IS 'Secure persistent log of portfolio inquiries received via /api/contact.';

-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Defense-in-depth: Never trust client-side authorization alone
-- =========================================================================

-- Enable RLS on both tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------------------
-- Policies for public.profiles
-- -------------------------------------------------------------------------

-- Policy: Users can view ONLY their own profile (cached auth.uid() via subquery)
CREATE POLICY "Users can view their own profile"
    ON public.profiles
    FOR SELECT
    USING ((select auth.uid()) = auth_user_id);

-- Policy: Users can update ONLY their own profile
CREATE POLICY "Users can update their own profile"
    ON public.profiles
    FOR UPDATE
    USING ((select auth.uid()) = auth_user_id)
    WITH CHECK ((select auth.uid()) = auth_user_id);

-- Policy: Service role has full access (for serverless sync endpoint)
CREATE POLICY "Service role full access on profiles"
    ON public.profiles
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- -------------------------------------------------------------------------
-- Policies for public.contact_submissions
-- -------------------------------------------------------------------------

-- Policy: Public & authenticated users can insert inquiries
CREATE POLICY "Anyone can submit contact inquiry"
    ON public.contact_submissions
    FOR INSERT
    WITH CHECK (true);

-- Policy: Authenticated users can view ONLY their own submitted inquiries
CREATE POLICY "Users can view their own inquiries"
    ON public.contact_submissions
    FOR SELECT
    USING (
        (select auth.uid()) IS NOT NULL AND 
        user_id IN (SELECT id FROM public.profiles WHERE auth_user_id = (select auth.uid()))
    );

-- Policy: Service role has full administrative access
CREATE POLICY "Service role full access on contact_submissions"
    ON public.contact_submissions
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- =========================================================================
-- Function: Auto-update updated_at timestamp (Hardened SECURITY INVOKER)
-- =========================================================================
CREATE OR REPLACE FUNCTION public.handle_profile_updated_at()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.handle_profile_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_profile_updated_at() FROM anon;
REVOKE EXECUTE ON FUNCTION public.handle_profile_updated_at() FROM authenticated;

DROP TRIGGER IF EXISTS trigger_profile_updated_at ON public.profiles;
CREATE TRIGGER trigger_profile_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_profile_updated_at();

